Repository nimblehq/github-notifications-mac, pull requests merged in 2021-09, with the labels that each got.

#45 [#4] [Chore] Set up the Project
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .gitignore
  Gemfile
  GithubNotifications.xcodeproj/project.pbxproj
  GithubNotifications.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  GithubNotifications.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  GithubNotifications.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GithubNotifications.xcodeproj/project.xcworkspace/xcuserdata/blys.xcuserdatad/UserInterfaceState.xcuserstate
  GithubNotifications.xcodeproj/xcuserdata/blys.xcuserdatad/xcschemes/xcschememanagement.plist
  GithubNotifications/GithubNotifications.entitlements
  GithubNotifications/Preview Content/Preview Assets.xcassets/Contents.json
  GithubNotificationsTests/GithubNotificationsTests.swift
  GithubNotificationsTests/Info.plist
  GithubNotificationsUITests/GithubNotificationsUITests.swift
  GithubNotificationsUITests/Info.plist
  Source/Application/AppDelegate/AppDelegate.swift
  Source/Application/Configurations/Plists/Info.plist
  Source/Application/Constants/Constants.swift
  Source/Application/LaunchScreen/Base.lproj/LaunchScreen.storyboard
  Source/Application/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Source/Application/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Source/Application/Resources/Assets.xcassets/Contents.json
  Source/Application/SceneDelegate/SceneDelegate.swift
  Source/Module/ContentView.swift
  Source/Services/Network/API/Base/API.swift
  Source/Services/Network/API/Base/BaseModels.swift
  Source/Services/Network/API/Base/Network+Typealias.swift
  Source/Services/Network/API/Base/Request.swift
  Source/Services/Network/API/Base/RequestConfiguration.swift
  Source/Services/Network/API/EndpointType.swift
  Source/Services/Network/API/GithubAPI.swift
  Source/Services/Network/API/GithubAPIError.swift
  Source/Services/Network/Factory/DecoderFactory.swift
  Source/Services/Network/Factory/NetworkServiceFactory.swift
Labels: type : chore

#48 [#46] Add yml to build when tag version
  .github/workflows/deploy_release.yml
  .gitignore
  GithubNotifications.xcodeproj/project.pbxproj
  GithubNotifications.xcodeproj/project.xcworkspace/xcuserdata/blys.xcuserdatad/UserInterfaceState.xcuserstate
  fastlane/Matchfile
  fastlane/fastfile
Labels: type : chore

#51 [15] [UI] As a logged-in user, I can see the empty repositories preferences screen
  GithubNotifications.xcodeproj/project.pbxproj
  Source/Application/Constants/Constants.swift
  Source/Application/SceneDelegate/SceneDelegate.swift
  Source/Extensions/Color+Hex.swift
  Source/Extensions/View+Border.swift
  Source/Module/ContentView.swift
  Source/Module/Repository/RepositoryScreen.swift
  Source/Views/Buttons/RoundedButtonStyle.swift
Labels: type : feature

#53 [#52] [Chore] Make Network layer more Combine-like
  Source/Services/Network/API/Base/API.swift
  Source/Services/Network/API/GithubAPI.swift
Labels: type : chore

#54 [CI] Fix fastlane match by adding readonly
  .github/workflows/test.yml
  fastlane/fastfile
Labels: type : chore

#50 [#7] [UI] As a user, I can log in with a Github Access Token
  GithubNotifications.xcodeproj/project.pbxproj
  GithubNotifications.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Source/Application/SceneDelegate/SceneDelegate.swift
  Source/Extensions/NSMutableAttributedString+Range.swift
  Source/Module/Login/LoginScreen.swift
  Source/Module/Login/Views/TextLabelWithHyperLink.swift
  Source/Module/Main/ContentView.swift
Labels: type : feature

#55 [#37] [Backend] As a logged-in user, I can receive notifications when someone requested your review.
  GithubNotifications.xcodeproj/project.pbxproj
  GithubNotifications.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Source/Application/Constants/Constants.swift
  Source/Application/SceneDelegate/SceneDelegate.swift
  Source/Models/APIModels/APINotification.swift
  Source/Models/APIModels/NotificationReason.swift
  Source/Services/Keychain/Keychain.swift
  Source/Services/Keychain/KeychainKey.swift
  Source/Services/Network/API/Base/RequestConfiguration.swift
  Source/Services/Network/API/EndpointType.swift
  Source/Services/Network/API/GithubAPI.swift
  Source/Services/Network/API/GithubAPIError.swift
  Source/Services/Network/Interceptors/AuthenticatedInterceptor.swift
  Source/Services/Network/RequestConfigurations/NotificationRequestConfiguration.swift
  Source/Services/Network/Services/NotificationsService.swift
Labels: type : feature

#58 [Chore] Add bump tag workflow
  .github/workflows/bump_tag.yml
Labels: type : chore

#59 [#44] [Integrate] As a logged-in user, I can fetch notification every one minute
  GithubNotifications.xcodeproj/project.pbxproj
  GithubNotifications.xcodeproj/project.xcworkspace/xcuserdata/blys.xcuserdatad/UserInterfaceState.xcuserstate
  GithubNotifications/GithubNotifications.entitlements
  Source/Application/AppDelegate/AppDelegate.swift
  Source/Application/Configurations/Plists/Info.plist
  Source/Application/SceneDelegate/SceneDelegate.swift
  Source/Services/Network/Factory/NetworkServiceFactory.swift
  Source/Services/Network/RequestConfigurations/NotificationRequestConfiguration.swift
  Source/Services/Network/Services/NotificationsService.swift
  Source/Services/NetworkPoll/NetworkPoll.swift
  fastlane/fastfile
Labels: type : feature

#57 [#10] [UI] As a logged-in user, I can see the general preferences screen
  GithubNotifications.xcodeproj/project.pbxproj
  GithubNotifications.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Source/Application/AppDelegate/AppDelegate.swift
  Source/Extensions/AppStorage+Key.swift
  Source/Module/General/GeneralScreen.swift
  Source/Module/General/GeneralScreenObservable.swift
  Source/Module/General/SettingSwitch/SettingSwitchView.swift
  Source/Module/General/SettingSwitch/SettingSwitchViewModel.swift
  Source/Services/Network/Factory/NetworkServiceFactory.swift
  Source/Views/Toggles/SwitchToggleStyle.swift
Labels: type : feature

#61 [Chore] change action for pushing new tag
  .github/workflows/bump_tag.yml
Labels: type : chore

#67 [66] [Bug] [Backend] As a Github User with no email in user object, I would like to be able to log in
  Source/Models/APIModels/APIUser.swift
Labels: type : bug

#71 [#12] As a logged-in user, I can see the account preferences screen
  GithubNotifications.xcodeproj/project.pbxproj
  Source/Module/Account/AccountScreen.swift
  Source/Module/Main/ContentView.swift
Labels: type : feature

#72 [#13] [Backend] As a logged-in user, I can see the account preferences screen
  GithubNotifications.xcodeproj/project.pbxproj
  Source/Services/Network/RequestConfigurations/UserRequestConfiguration.swift
  Source/Services/Network/Services/UserService.swift
Labels: type : chore

#70 [#65] [Integation] As a logged-in user, when I logout I want to clear my network cache so I can login with the same user.
  Source/Module/Login/LoginScreen.swift
  Source/Module/Login/LoginViewModel.swift
  Source/Services/Network/RequestConfigurations/UserRequestConfiguration.swift
  Source/Services/Network/Services/UserService.swift
Labels: type : feature

#74 [Chore] Add greeting bot to issue
  .github/workflows/greetings_demo.yml
Labels: type : chore

#78 [#14] [Integrate] As a logged-in user, I can see the account preferences screen
  GithubNotifications.xcodeproj/project.pbxproj
  Source/Module/Account/AccountScreen.swift
  Source/Module/Account/AccountViewModel.swift
  Source/Module/Main/ContentView.swift
Labels: type : feature

#75 [#44] [Integrate] As a logged-in user, I can fetch notification every one minute
  Source/Services/Network/RequestConfigurations/NotificationRequestConfiguration.swift
Labels: type : feature

#83 [#82] Add filter for older notifications
  Source/Extensions/AppStorage+Key.swift
  Source/Services/NetworkPoll/NetworkPoll.swift
Labels: type : feature

#84 [#42][Integrate] As a logged-in user, when I press on the notification banner it will open the Github website with my default browser
  Source/Utilities/NotificationManager.swift
Labels: type : feature

#89 [85] [Backend] As a logged-in user, I want to add my private repo if I have access
  Source/Services/Network/Factory/NetworkServiceFactory.swift
  Source/Services/Network/RequestConfigurations/RepositoryRequestConfiguration.swift
  Source/Services/Network/Services/RepositoryService.swift
Labels: type : feature

#90 [#88] [UI] As a logged in user, I want to see which tab I'm selecting
  Source/Module/Main/ContentView.swift
Labels: type : feature

#91 [#86] [Integration] As a logged in user, I want to see my GitHub username on the Account screen
  Source/Module/Account/AccountViewModel.swift
Labels: type : feature

#92 [#11] [Integrate] As a logged-in user, I can see the general preferences screen
  Source/Utilities/NotificationManager.swift
Labels: type : feature

#93 [#77] [Bug] When scrolling Search Repo list, sometimes the scroll view freezes. #77
  Source/Module/SearchRepository/Views/SearchBar.swift
Labels: type : bug

#97 [#94] [Chore] Fix Zip Logic in CI
  fastlane/fastfile
Labels: type : chore

#102 [#42] Fix wrong PR URL
  Source/Application/AppDelegate/AppDelegate.swift
  Source/Models/APIModels/APINotification.swift
Labels: type : bug

#104 [#98] [Integrate] As a logged-in user, when I turn off the option repeat review requested notifications in general screen, I will not get old review requested notifications anymore
  Source/Module/General/GeneralScreen.swift
  Source/Module/General/GeneralScreenObservable.swift
  Source/Utilities/NotificationManager.swift
Labels: type : feature

#105 [#99] [Integrate] As a logged-in user, when I press on the review request notification banner, in case I enable the option repeat review requested notification, I don't want to show that banner again
  Source/Utilities/NotificationManager.swift
Labels: type : feature
